### ISSUE TITLE
sphinx-intl is not reading SPHINXOPTS

### ISSUE THREAD

**Issue by clalarco** [sphinx-doc/sphinx-intl#17]
Hi:

I use tags inside conf.py for some variables required by the filenames, in particular to set htmlhelp_basename. 

To do this  I use SPHINXOPTS=-tdoc1 or SPHINXOPTS=-tdoc2, and in conf.py:

```
if tags.has('doc1'):
    htmlhelp_basename = 'doc1'
elif tags.has('doc2'):
    htmlhelp_basename = 'doc2'
```

However, these options are not used when reading conf.py, hence the sphinx-intl fails.

Any help will be appreciated, thanks.

**Comment by shimizukawa** [comment]
Hi,

`sphinx-intl` is no a part of sphinx. So "hence the sphinx-build fails." is related to sphinx instead of sphinx-intl.

If the problem is related to the `sphinx-intl` command, please let me know a bit more detailed situation. If you are having problems with sphinx-build command, please report it to https://github.com/sphinx-doc/sphinx/issues.

Thanks.

**Comment by clalarco** [comment]
I fixed the typo, I meant sphinx-intl, not sphinx-build.

**Comment by shimizukawa** [comment]
Thanks for updating the information.
I still can't understand why `sphinx-intl` fails when you can't specify `htmlhelp_basename` ? How was it displayed when failing?

**Comment by clalarco** [comment]
Yeah, this variable was created by me a long time ago :S

Here's some steps to reproduce the issue from a blank project:

1. Create a blank project using sphinx-quickstart. Set required fields and leave all the rest as default.
2. Edit conf.py where master_doc is set and locale directory (and a print to show tags):

```
# The master toctree document.
print("tags: " + str([t for t in tags]))
if tags.has('doc1'):
    master_doc = 'index_doc1'
elif tags.has('doc2'):
    master_doc = 'index_doc2'

# Add locale directory:
locale_dirs = ['locale/']
```

3. make a copy of index.rst to index_doc1.rst and index_doc2.rst

4. Create doc1 and doc2 (works fine):

```
$SPHINXOPTS="-tdoc1" make singlehtml`
tags: ['doc1']
...
```

```
$SPHINXOPTS="-tdoc2" make singlehtml`
tags: ['doc2']
...
```

5. Create gettext for doc1 and doc2 (also works fine) index.pot, index_doc1.pot and index_doc2.pot are created at _build\gettext directory:
```
$SPHINXOPTS="-tdoc1" make gettext`
tags: ['doc1']
...
```

```
$SPHINXOPTS="-tdoc2" make gettext`
tags: ['doc2']
...
```

6. Create po from pot files. It fails:
```
$SPHINXOPTS="-tdoc1" sphinx-intl update -l es -p _build/gettext
tags: []
...
  File "conf.py", line 151, in <module>
    (master_doc, 'doc.tex', u'doc Documentation',
NameError: name 'master_doc' is not defined
```

**Comment by clalarco** [comment]
I did a pull request with a proposal.

**Comment by shimizukawa** [comment]
Thanks!
